# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['pdf2csv.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['pymupdf'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 字体子集化（pymupdf 只在可选功能中用到，可以安全排除）
        'fontTools', 'fontTools.*',
        # 异步/网络协议（PDF 注释不需要）
        'asyncio', 'http', 'ftplib', 'smtplib', 'poplib', 'imaplib',
        'nntplib', 'telnetlib', 'requests',
        # 调试器/REPL/测试
        'pdb', 'doctest', 'unittest', '_pyrepl',
        'bdb', 'cmd', 'rlcompleter', 'pydoc',
        # GUI/Web 框架/数值计算
        'numpy', 'scipy', 'PIL', 'matplotlib', 'tkinter',
        'PyQt5', 'PyQt6', 'PySide2', 'PySide6', 'wx', 'curses',
        'torch', 'tensorflow', 'django', 'flask', 'fastapi',
        'jupyter', 'notebook', 'pandas', 'openpyxl',
        # 其他 PDF/图片扩展
        'PyPDF2', 'pdfplumber', 'pdf2image',
        # 其他不需要的标准库/工具
        'uuid', 'shelve', 'dbm',
        # 除中英文之外的大部分编码（保留 ascii/latin_1/utf_8/中文相关）
        'encodings.cp037', 'encodings.cp1006', 'encodings.cp1026',
        'encodings.cp1125', 'encodings.cp1140', 'encodings.cp1250',
        'encodings.cp1251', 'encodings.cp1253',
        'encodings.cp1254', 'encodings.cp1255', 'encodings.cp1256',
        'encodings.cp1257', 'encodings.cp1258', 'encodings.cp273',
        'encodings.cp424', 'encodings.cp500', 'encodings.cp720',
        'encodings.cp737', 'encodings.cp775', 'encodings.cp850',
        'encodings.cp852', 'encodings.cp855', 'encodings.cp856',
        'encodings.cp857', 'encodings.cp858', 'encodings.cp860',
        'encodings.cp861', 'encodings.cp862', 'encodings.cp863',
        'encodings.cp864', 'encodings.cp865', 'encodings.cp866',
        'encodings.cp869', 'encodings.cp874', 'encodings.cp875',
        'encodings.cp932', 'encodings.cp949', 'encodings.cp950',
        'encodings.euc_jis_2004', 'encodings.euc_jisx0213',
        'encodings.euc_jp', 'encodings.euc_kr',
        'encodings.iso2022_jp', 'encodings.iso2022_jp_1',
        'encodings.iso2022_jp_2', 'encodings.iso2022_jp_2004',
        'encodings.iso2022_jp_3', 'encodings.iso2022_jp_ext',
        'encodings.iso2022_kr', 'encodings.iso8859_1',
        'encodings.iso8859_10', 'encodings.iso8859_11',
        'encodings.iso8859_13', 'encodings.iso8859_14',
        'encodings.iso8859_15', 'encodings.iso8859_16',
        'encodings.iso8859_2', 'encodings.iso8859_3',
        'encodings.iso8859_4', 'encodings.iso8859_5',
        'encodings.iso8859_6', 'encodings.iso8859_7',
        'encodings.iso8859_8', 'encodings.iso8859_9',
        'encodings.johab', 'encodings.koi8_r', 'encodings.koi8_t',
        'encodings.koi8_u', 'encodings.kz1048', 'encodings.mac_arabic',
        'encodings.mac_croatian', 'encodings.mac_cyrillic',
        'encodings.mac_farsi', 'encodings.mac_greek',
        'encodings.mac_iceland', 'encodings.mac_latin2',
        'encodings.mac_roman', 'encodings.mac_romanian',
        'encodings.mac_turkish', 'encodings.palmos',
        'encodings.ptcp154', 'encodings.oem',
        'encodings.shift_jis', 'encodings.shift_jis_2004',
        'encodings.shift_jisx0213', 'encodings.tis_620',
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='pdf2csv',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
